# Generated by Django 3.2.3 on 2021-06-20 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ADCampaigns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('channel', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=2)),
                ('os', models.CharField(max_length=50)),
                ('impressions', models.IntegerField(default=0)),
                ('clicks', models.IntegerField(default=0)),
                ('installs', models.IntegerField(default=0)),
                ('spend', models.FloatField(default=0.0)),
                ('revenue', models.FloatField(default=0.0)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
